//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVoucher.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debit
    {
        public long DebitId { get; set; }
        public string Username { get; set; }
        public string OldValue { get; set; }
        public string Amount { get; set; }
        public string NewValue { get; set; }
        public string InFlight { get; set; }
    }
}
