//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVoucher.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long TransactionId { get; set; }
        public string Username { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public int CostPrice { get; set; }
        public int Saleprice { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
