// <auto-generated />
namespace NVoucher.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class nv3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nv3));
        
        string IMigrationMetadata.Id
        {
            get { return "201403201457239_nv3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
