// <auto-generated />
namespace NVoucher.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class voucher15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(voucher15));
        
        string IMigrationMetadata.Id
        {
            get { return "201401162115130_voucher15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
