//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVoucher.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance
    {
        public long BalanceId { get; set; }
        public string Value { get; set; }
        public string InFlight { get; set; }
        public string AspNetUserId { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
