//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVoucher.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debit
    {
        public Debit()
        {
            this.Tranges = new HashSet<Transaction>();
        }
    
        public long DebitId { get; set; }
        public string AspNetUserId { get; set; }
        public string OldValue { get; set; }
        public string Amount { get; set; }
        public string NewValue { get; set; }
        public string InFlight { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Transaction> Tranges { get; set; }
    }
}
