//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVoucher.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Country { get; set; }
        public bool Term { get; set; }
        public long Numbers { get; set; }
        public bool IsVerified { get; set; }
        public string Email { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
