//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVoucher.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long TranxId { get; set; }
        public string AspNetUserId { get; set; }
        public long DebitOrderId { get; set; }
        public string ProductCode { get; set; }
        public string CostPrice { get; set; }
        public string SalePrice { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Debit Debit { get; set; }
    }
}
